# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 354b6cb156c96b6472277b588bb64ec48b07a2df85ae7afbf3e076e869e2c4b3d07c5cde135ba23716f16116ce3edad36048e9674a74855868f51c9223ef1d76

test:
  secret_key_base: f57a1004b7f4882ce99a5b0e10b071c4212a51b22f13afac4de7f919a47aa8e8a76708917dcebee7dc5b42b47ddc3cb962596c21749f725ff6a855bbd05d6e9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
